### PR TITLE
[Bug] Fix row type decimal convert bug

### LINKED ISSUE #25: [Bug] Row type decimal convert bug
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0

### What's Wrong?

Scale conversion error when querying decimal type field. For example, 30 is converted to 0.03.

### What You Expected?

 30 is converted to 30.

### How to Reproduce?

Query decimal type field.

### Anything Else?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by aiwenmo**
# Proposed changes

Issue Number: close #25 

## Problem Summary:

Add deserialize in DorisRowDataInputFormat.nextRecord

## Checklist(Required)

1. Does it affect the original behavior: (Yes)
2. Has unit tests been added: (No)
3. Has document been added or modified: (No Need)
4. Does it need to update dependencies: (No)
5. Are there any changes that cannot be rolled back: (No)

## Further comments

This is a small bug.

### CODE REVIEW

File: flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java [hunk 1]
```diff
@@ -136,15 +146,30 @@ public RowData nextRecord(RowData reuse) throws IOException {
...
 
+    private Object deserialize(LogicalType type, Object val) {
+        switch (type.getTypeRoot()) {
+            case DECIMAL:
+                final DecimalType decimalType = ((DecimalType) type);
+                final int precision = decimalType.getPrecision();
+                final int scala = decimalType.getScale();
+                return DecimalData.fromBigDecimal((BigDecimal) val, precision, scala);
+            case VARCHAR:
+                return StringData.fromString(val.toString());
```
Comment (JNSimba) [inline flink-doris-connector/src/main/java/org/apache/doris/flink/table/DorisRowDataInputFormat.java:167]: The StringData.fromString conversion in Rowbatch should be removed, otherwise an error may be reported here: StringData cannot be cast to java.lang.String

**Review by JNSimba — APPROVED** [review]
LGTM
